fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
struct_field_align_threshold = 40
use_field_init_shorthand = true
use_small_heuristics = "Max"
