name: CI
on:
  push:
    branches: ["master"]
    tags: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  fmt:
    name: rustfmt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: default
          default: true
          components: rustfmt
      - run: cargo fmt --all -- --check
      - uses: crate-ci/typos@master
  lint-test:
    name: clippy lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          default: true
          components: clippy
      - uses: actions/cache@v2
        with:
          path: |
            /home/runner/.cargo
            **/target
          key: ${{ hashFiles('**/Cargo.lock') }}-cov
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          name: clippy
  build:
    name: build executable
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          default: true
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          path: target/release/lpl.exe
        if: matrix.os == 'windows-latest'
      - uses: actions/upload-artifact@v4
        with:
          path: target/release/lpl
        if: matrix.os == 'ubuntu-latest'
      - uses: actions/upload-artifact@v4
        with:
          path: target/release/lpl-macos
          name: lpl
        if: matrix.os == 'macos-latest'

